apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: lightweight-otel-demo
  title: Lightweight Otel Demo
  description: Microservices system from
    https://github.com/BimsaraAnjanaJay/lightweight-otel-demo
  annotations:
    github.com/project-slug: BimsaraAnjanaJay/lightweight-otel-demo
spec:
  owner: team-platform
  domain: microservices

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth
  title: Auth
  description: nodejs microservice
  annotations:
    jaegertracing.io/service-name: auth
    tracing.opentelemetry/instrumented: "true"
    github.com/project-slug: BimsaraAnjanaJay/lightweight-otel-demo
spec:
  type: service
  lifecycle: production
  owner: team-platform
  system: lightweight-otel-demo

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway
  title: Gateway
  description: nodejs microservice
  annotations:
    jaegertracing.io/service-name: gateway
    tracing.opentelemetry/instrumented: "true"
    github.com/project-slug: BimsaraAnjanaJay/lightweight-otel-demo
spec:
  type: service
  lifecycle: production
  owner: team-platform
  system: lightweight-otel-demo

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product
  title: Product
  description: nodejs microservice
  annotations:
    jaegertracing.io/service-name: product
    tracing.opentelemetry/instrumented: "true"
    github.com/project-slug: BimsaraAnjanaJay/lightweight-otel-demo
spec:
  type: service
  lifecycle: production
  owner: team-platform
  system: lightweight-otel-demo
