/*
 * Copyright 2025 The Backstage Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as fs from 'fs-extra';
import * as path from 'path';
import { LoggerService } from '@backstage/backend-plugin-api';

/**
 * For every immediate subdirectory of repoPath that contains a Node.js app,
 * writes an `otel-server.js` file that:
 *  - Loads @opentelemetry/auto-instrumentations-node/register (reliable require, no NODE_OPTIONS)
 *  - If the service has its own app.listen(), just requires index.js
 *  - If the service only exports a router (no app.listen()), wraps it in Express
 *
 * The startup command in the generated compose always uses `node otel-server.js`
 * so this is the single reliable entry point for OTEL + the service.
 */
export async function createServerWrappers(
  repoPath: string,
  logger: LoggerService,
): Promise<void> {
  let entries: fs.Dirent[];
  try {
    entries = await fs.readdir(repoPath, { withFileTypes: true });
  } catch {
    return;
  }

  for (const entry of entries) {
    if (!entry.isDirectory() || entry.name.startsWith('.')) continue;

    const servicePath = path.join(repoPath, entry.name);
    const indexPath = path.join(servicePath, 'index.js');

    if (!(await fs.pathExists(indexPath))) continue;

    const content = await fs.readFile(indexPath, 'utf-8');
    const hasServer = content.includes('.listen(');
    const isRouterModule = !hasServer && content.includes('module.exports');

    if (!hasServer && !isRouterModule) continue;

    const wrapperPath = path.join(servicePath, 'otel-server.js');

    if (hasServer) {
      // Service already has an HTTP server — just load OTEL register then require the app
      await fs.writeFile(
        wrapperPath,
        `// Auto-generated by FRA: loads OTEL then starts the existing HTTP server
require('@opentelemetry/auto-instrumentations-node/register');
require('./index.js');
`,
      );
      logger.info(
        `📡 Created OTEL wrapper for ${entry.name} (delegates to index.js server)`,
      );
    } else {
      // Router-only service — wrap in a minimal Express server
      await fs.writeFile(
        wrapperPath,
        `// Auto-generated by FRA: wraps exported router in a standalone Express server with OTEL
require('@opentelemetry/auto-instrumentations-node/register');
const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

try {
  const router = require('./index.js');
  if (router && typeof router === 'function') {
    app.use('/', router);
  }
} catch (e) {
  console.error('[otel-server] Failed to load router:', e.message);
}

app.get('/health', (_req, res) => res.json({ status: 'ok', service: '${entry.name}' }));

app.listen(PORT, () => {
  console.log('[otel-server] ${entry.name} running on port ' + PORT);
});
`,
      );
      logger.info(
        `📦 Created OTEL + HTTP server wrapper for ${entry.name} (index.js exports router without listen)`,
      );
    }
  }
}
